# Generated by Django 4.2.1 on 2023-05-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_to',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.state'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
