# Generated by Django 4.2 on 2023-06-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_orderitem_total_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_commission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
