# Generated by Django 4.2 on 2023-06-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cartitem_total_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_commission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
