# Generated by Django 4.2.1 on 2023-07-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cartitem_total_alter_cartitem_total_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='befor_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
