# Generated by Django 4.2.1 on 2023-07-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productrating_product_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='reply',
            field=models.TextField(blank=True),
        ),
    ]
