# Generated by Django 4.2.1 on 2023-07-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_productrating_comment_productrating_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='reply',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
